### ISSUE TITLE
About memory management in Program4_2.cpp

### ISSUE THREAD

**Issue by derekli66** [wiselyku/Algorithms#1]
I have ever seen the question like this,
How to handle memory allocation and release in binary search tree?
Link list is not like BST but they have a common place that they have a root node connecting to next node.

I saw you use `new` to create a new node but did not release it before end of program. I think it could be an interview question when we are solving algorithm with Cpp. 

Wish this helps ^_^

**Comment by wiselyku** [comment]
Yes, if we need to manage the memory well, I should write a function to release the whole linked list or just loop to release the linked list. Otherwise, the memory will still be occupied. Up to now, I just focus on the algorithm design. Thank you very much.
